# Generated by Django 5.0.8 on 2024-08-07 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_score_player_score_player_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('player_name', 'player_id', 'score', 'created_at')},
        ),
    ]
